### PR TITLE
Some new env variables to control additional configuration parameters

### PR DESCRIPTION
**Pull request by juanluisbaptiste**
Hi David,

This PR adds the following new env variables to configure additional nginx and php-fpm parameters:

* _ENABLE_GZIP_COMPRESSION=(true|false)_: Enables gzip compression. Default is true.
* _WORKER_PROCESSES_: to set nginx worker_processes parameter. Default is _auto_.
* _WORKER_CONNECTIONS_: to set nginx worker_connections parameter. Default is 4096.
* _FPM_MAX_CHILDREN_: to set php-fpm worker_processes. Default is 75.
* _FPM_MAX_REQUESTS_: to set php-fpm worker_requests. Default is 500.

Also I added nginx _tcp_nodelay_ nginx option as recommended [here](https://thoughts.t37.net/nginx-optimization-understanding-sendfile-tcp-nodelay-and-tcp-nopush-c55cdd276765).

Also, I think the child images shouldn't include their own copy of the configuration files (like nginx/conf.d/default.conf) and instead rely on the available env variables. If they are not enough the can ask for more variables to be added, or create their own custom image that includes their own custom config files can be a better approach.

### CODE REVIEW

**Comment by tiredofit** [comment]
Nice stuff. I'm looking forward to using in our own environment.

**Comment by juanluisbaptiste** [comment]
Excellent, I'll merge these commits on the other branches tonight.

**Comment by juanluisbaptiste** [comment]
And there are lots of parameters we could add env vars to, those were the ones I was needing ATM.

**Comment by tiredofit** [comment]
Sure - there is a tonne of changes that could be made (compression level and so on). I eventually want to switch these over to start using tiredofit/nginx as a base just for easier management along with a bunch more additions. My time lately has been focused on keeping my organization going, but with that involves training a few people on Docker so I'll make a point to make a wishlist and when I'm comfortable with them being able to make the changes lay on the feature list :)

**Comment by tiredofit** [comment]
Hold on any more merges for time being. You gave me the motivation to revamp the images properly. You will like. Will be a couple days max.

**Comment by juanluisbaptiste** [comment]
Sure.

**Comment by tiredofit** [comment]
OK, pushed and now relying on tiredofit/nginx as base (lots of options) and cleaned up the PHP images drastically. I know we met re the Wordpress Image, that's been updated to.

I don't think you'll see any breakage with your existing environment variables, just note that some have changed, as I was starting to see duplicates across the images. Let me know if this gives you what you need :)

**Pull request merged**
